/* CRIA O BANCO DE DADOS */
CREATE DATABASE LIVRARIA;

/* ACESSA O BANCO DE DADOS "LIVRARIA" */
USE LIVRARIA;

/* CRIA A TABELA "LIVROS" NO BD "LIVRARIA", ESTABELECE O ESQUEMA E DEFINE OS TIPOS DOS DADOS */
CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(50),
	NOME_AUTOR VARCHAR(50),
	SEXO_AUTOR CHAR(9), /* É interessante colocar como CHAR(1) quando for se referir ao sexo, pois ficará como "M" ou "F", ocupando menos bytes no BD e melhorando a performance dele. */
	NUM_PAGINAS INT(4),
	NOME_EDITORA VARCHAR(30),
	VALOR FLOAT(6,2),
	UF CHAR(2),
	ANO_PUBLICADO INT(4)
);

/* MOSTRA AS TABELAS (TABLES) PRESENTES NO BANCO DE DADOS "LIVRARIA" */
SHOW TABLES;

/* DESCREVE AS CARACTERISTICAS DA TABELA "LIVROS" */
DESC LIVROS;

/* ADICIONA (INSERT INTO) OS VALORES (VALUES) DENTRO DA TABELA LIVROS */
INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUM_PAGINAS, NOME_EDITORA, VALOR, UF, ANO_PUBLICADO) VALUES('Cavaleiro Real','Ana Claudia','Femenino','465','Atlas',49.9,'RJ',2009),
	('SQL para Leigos','João Nunes','Masculino',450,'Addison',98,'SP',2018),
	('Receitas Caseiras','Celia Tavares','Femenino',210,'Atlas',45,'RJ',2008),
	('Pessoas Efetivas','Eduardo Santos','Masculino',390,'Beta',78.99,'RJ',2018),
	('Hábitos Saudáveis','Eduardo Santos','Masculino',630,'Beta',150.98,'RJ',2019),
	('A Casa Marrom','Hermes Macedo','Masculino',250,'Bubba',60,'MG',2016),
	('Estacio Querido','Geraldo Francisco','Masculino',310,'Insignia',100,'ES',2015),
	('Pra sempre amigas','Leda Silva','Femenino',510,'Insignia',78.98,'ES',2011),
	('Copas Inesquecíveis','Marco Alcantara','Masculino',200,'Larson',130.98,'RS',2018),
	('O poder da mente','Clara Mafra','Femenino',120,'Continental',56.58,'RS',2017)
  ;

/* PROJETA TODA A TABELA "LIVROS" DO BANCO DE DADOS "LIVRARIA" NA TELA SEM NENHUM FILTRO */
SELECT * FROM LIVROS;

/* PROJETA OS CAMPOS "NOME_LIVRO" E "NOME_EDITORA" DA TABELA "LIVROS" */
SELECT NOME_LIVRO, NOME_EDITORA FROM LIVROS;

/* PROJETA OS CAMPOS "NOME_LIVRO" E "UF" DA TABELA "LIVROS" ADICIONANDO UM FILTRO ONDE O SEXO DO AUTOR (SEXO_AUTOR) SEJA "MASCULINO" */
SELECT NOME_LIVRO, UF FROM LIVROS WHERE SEXO_AUTOR = "Masculino";

/* PROJETA OS CAMPOS "NOME_LIVRO" E "NUM_PAGINAS" DA TABELA "LIVROS" ADICIONANDO UM FILTRO ONDE O SEXO DO AUTOR (SEXO_AUTOR) SEJA "FEMENINO" */
SELECT NOME_LIVRO, NUM_PAGINAS FROM LIVROS WHERE SEXO_AUTOR = "Femenino";

/* PROJETA O CAMPOS "VALOR" DA TABELA "LIVROS" ONDE A UF SEJA IGUAL A "SP" */
SELECT VALOR FROM LIVROS WHERE UF = "SP";

/* PROJETA OS CAMPOS "NOME_LIVRO" E "SEXO_AUTOR" DA TABELA "LIVROS" ADICIONANDO UM FILTRO ONDE O SEXO DO AUTOR (SEXO_AUTOR) SEJA "MASCULINO" E O CAMPO "UF" SEJA IGUAL A "SP" OU "RJ" */
SELECT NOME_AUTOR, SEXO_AUTOR FROM LIVROS WHERE SEXO_AUTOR = "Masculino" AND (UF = "SP" OR UF = "RJ");
